init_sacks:
  - "mining_sack"
  - "farming_sack"
sack_menu:
  inventory:
    - "ooooooooo"
    - "c       c"
    - "c       c"
    - "c       c"
    - "c       c"
    - "ooooooooo"
  material_item:
    lore:
      - "&fКоличество: &a{count}/{max}"
      - "&a&lНажмите&f, чтобы достать из мешочка"
    custommodeldata: 0
  decoration:
    o:
      name: ""
      material: BLUE_STAINED_GLASS_PANE
      lore:
        - ""
      custommodeldata: 0
    c:
      name: ""
      material: GREEN_STAINED_GLASS_PANE
      lore:
        - ""
      custommodeldata: 0
  collect_all:
    name: "&a&lПолучить всё"
    material: CHEST
    lore:
      - "&a&lНажмите&f, чтобы получить всё"
    custommodeldata: 0
items:
  mining_sack:
    name: "&aМешочек шахтёра"
    material: LEATHER_HORSE_ARMOR
    custommodeldata: 10002
    color: 0x777777
    lore:
      - ""
      - "&a&lПКМ&f - открыть мешочек"
    pickupMaterials:
      - COBBLESTONE
      - GRANITE
      - DIORITE
  farming_sack:
    name: "&eМешочек фермера"
    material: LEATHER_HORSE_ARMOR
    custommodeldata: 10002
    color: 0xc47e19
    lore:
      - ""
      - "&a&lПКМ&f - открыть мешочек"
    pickupMaterials:
      - WHEAT
      - CARROT
      - POTATO
      - BEETROOT
      - COCOA_BEANS
      - NETHER_WART
messages:
  configReloaded: "&aКонфигурация успешно перезагружена!"
  noPermission: "&cУ вас нет прав для выполнения данной команды"